# Generated by Django 5.0.1 on 2026-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('patent_id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_country', models.CharField(blank=True, max_length=10, null=True)),
                ('publication_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('publication_kind', models.CharField(blank=True, max_length=10, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('application_type', models.CharField(blank=True, max_length=50, null=True)),
                ('application_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('application_series_code', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('classifications_ipcr', models.JSONField(blank=True, null=True)),
                ('classifications_cpc_main', models.JSONField(blank=True, null=True)),
                ('classifications_cpc_further', models.JSONField(blank=True, null=True)),
                ('inventors', models.JSONField(blank=True, null=True)),
                ('applicants', models.JSONField(blank=True, null=True)),
                ('claims', models.JSONField(blank=True, null=True)),
                ('priority_claims', models.JSONField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publication_date', '-patent_id'],
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('search_query', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patents', models.ManyToManyField(related_name='searches', to='accounts.patent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
