# Generated by Django 5.0.1 on 2026-02-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patent_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(choices=[('inventor', 'Inventor'), ('applicant', 'Applicant'), ('assignee', 'Assignee')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patents', models.ManyToManyField(related_name='entities', to='accounts.patent')),
                ('searches', models.ManyToManyField(related_name='entities', to='accounts.search')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'entity_type')},
            },
        ),
    ]
