# Generated by Django 5.0.1 on 2026-02-20 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='accounts.patent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
