# Generated by Django 5.0.1 on 2026-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
