# Generated by Django 5.0.1 on 2026-02-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='parsed_risks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
