# Generated by Django 5.0.1 on 2026-04-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_parsed_risks'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_data', models.JSONField(default=dict)),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
                ('patent_count', models.IntegerField(default=0)),
                ('risks_count', models.IntegerField(default=0)),
                ('patents_with_military', models.IntegerField(default=0)),
                ('patents_with_surveillance', models.IntegerField(default=0)),
                ('is_global', models.BooleanField(default=False)),
                ('saved_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_cache', to='accounts.savedsearch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dashboard caches',
                'ordering': ['-cached_at'],
                'unique_together': {('user', 'saved_search')},
            },
        ),
    ]
