# Generated by Django 5.0.1 on 2026-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_dashboard_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcache',
            name='patents_with_online_manipulation',
            field=models.IntegerField(default=0),
        ),
    ]
