# Generated by Django 5.0.1 on 2026-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_patents_with_online_manipulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardcache',
            options={'ordering': ['-cached_at']},
        ),
        migrations.AddField(
            model_name='dashboardcache',
            name='total_patent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboardcache',
            name='total_risks',
            field=models.IntegerField(default=0),
        ),
    ]
