# Generated by Django 5.0.1 on 2026-06-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_dashboardcache_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='ticker',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
