# Generated by Django 5.0.1 on 2026-06-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_ticker_to_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='ticker',
            field=models.CharField(blank=True, help_text='Stock ticker symbol', max_length=10, null=True),
        ),
    ]
